site_name: Reloaded Hooks NexGen
site_url: https://github.com/Reloaded-Project/Reloaded.Hooks-rs

repo_name: Reloaded-Project/Reloaded.Hooks-rs
repo_url: https://github.com/Reloaded-Project/Reloaded.Hooks-rs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Reloaded-Project
    # - icon: fontawesome/brands/twitter
    #  link: https://twitter.com/thesewer56?lang=en-GB

extra_css:
  - Reloaded/Stylesheets/extra.css

markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist
  - def_list
  - meta
  - md_in_html
  - attr_list
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

theme:
  name: material
  palette:
    scheme: reloaded3-slate
  features:
    - navigation.instant

plugins:
  - search

nav:
  - Home: index.md
  - Library Internals:
    - Design Docs: 
      - Common Notes: dev/design/common.md
      - Function Hooks: 
        - Overview: dev/design/function-hooks/overview.md
        - Hooking Strategy: 
          - General: dev/design/function-hooks/hooking-strategy.md
          - x86: dev/design/function-hooks/hooking-strategy-x86.md
          - ARM64: dev/design/function-hooks/hooking-strategy-arm64.md
        - Wrapper Generation: dev/design/function-hooks/wrappers.md
      - Assembly Hooks: dev/design/assembly-hooks/overview.md
      - Branch Hooks: dev/design/branch-hooks/overview.md
      - VTable Hooks: dev/design/vtable-hooks/overview.md
    - Architectures:
      - Overview: dev/arch/overview.md
      - Operations: dev/arch/operations.md
      - Operations (Implemented): dev/arch/operations-impl.md
      - x86:
        - Overview (x86): dev/arch/x86/x86.md
        - Overview (x86_64): dev/arch/x86/x86_64.md
        - Code Relocation: dev/arch/x86/code_relocation.md
      - arm64: 
        - Overview: dev/arch/arm64/aarch64.md
        - Code Relocation: dev/arch/arm64/code_relocation.md
    - Platform Support: dev/platform/overview.md
  - Contributing: contributing.md
  - License: Reloaded/Pages/license.md
  - How to Document: Reloaded/Pages/contributing.md